/* ============================================================
   Suretofind — Job Dataset
   Compiled from: LinkedIn "Jobs on the Rise" 2026, BLS Occupational
   Outlook Handbook (2024–2034 projections), WEF Future of Jobs
   Report 2025, and O*NET/RIASEC occupational data.

   riasec values are 0–1 weights on Holland's six types:
   R = Realistic, I = Investigative, A = Artistic,
   S = Social, E = Enterprising, C = Conventional

   degree: "none" | "cert" | "bachelor" | "graduate"
   remote: "remote" | "hybrid" | "onsite" | "flexible"
   setting: "indoor" | "outdoor" | "mixed"
   collab: "solo" | "team" | "mixed"
   pace: "structured" | "flexible"
   risk: "stable" | "growth"   (stable = established/steady demand,
                                  growth = fast-rising / more volatile)
   ============================================================ */

const JOBS = [
  {
    id: "ai-engineer",
    title: "AI Engineer",
    category: "Tech & AI",
    riasec: { R: 0.1, I: 0.95, A: 0.3, S: 0.15, E: 0.3, C: 0.4 },
    blurb: "Builds and ships AI-powered systems — from model integration to production pipelines.",
    skills: ["Python", "ML frameworks (PyTorch)", "RAG / LLM tooling", "Systems thinking", "Debugging complex pipelines"],
    education: "Bachelor's in CS or related field common; portfolio + bootcamp paths increasingly viable",
    degree: "bachelor",
    salary: "$125K – $210K+",
    growth: "#1 fastest-rising role, LinkedIn 2026; computer/math occupations +10.1% (BLS)",
    remote: "hybrid",
    setting: "indoor",
    collab: "mixed",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "ai-consultant",
    title: "AI Consultant & Strategist",
    category: "Tech & AI",
    riasec: { R: 0.05, I: 0.75, A: 0.25, S: 0.55, E: 0.85, C: 0.35 },
    blurb: "Helps organizations figure out where and how to responsibly adopt AI.",
    skills: ["Business analysis", "AI literacy", "Client communication", "Change management"],
    education: "Bachelor's typical; often paired with technical or MBA background",
    degree: "bachelor",
    salary: "$110K – $190K",
    growth: "#2 fastest-rising role, LinkedIn 2026",
    remote: "hybrid",
    setting: "indoor",
    collab: "team",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    category: "Tech & AI",
    riasec: { R: 0.05, I: 0.95, A: 0.15, S: 0.1, E: 0.2, C: 0.55 },
    blurb: "Turns messy data into models and decisions using statistics and machine learning.",
    skills: ["Statistics", "Python / R", "SQL", "Data visualization", "Business storytelling"],
    education: "Bachelor's or master's in a quantitative field typical",
    degree: "bachelor",
    salary: "$95K – $165K (BLS median $112,590)",
    growth: "+34% through 2034 (BLS) — 4th-fastest US occupation",
    remote: "hybrid",
    setting: "indoor",
    collab: "mixed",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "data-annotator",
    title: "Data Annotator",
    category: "Tech & AI",
    riasec: { R: 0.1, I: 0.55, A: 0.1, S: 0.05, E: 0.05, C: 0.85 },
    blurb: "Labels and reviews the data that trains AI models — precision work behind the scenes.",
    skills: ["Attention to detail", "Pattern recognition", "Following rubrics precisely", "Basic tech comfort"],
    education: "No degree required — most roles are trained on the job",
    degree: "none",
    salary: "$38K – $65K",
    growth: "#4 fastest-rising role, LinkedIn 2026",
    remote: "remote",
    setting: "indoor",
    collab: "solo",
    pace: "structured",
    risk: "growth"
  },
  {
    id: "infosec-analyst",
    title: "Information Security Analyst",
    category: "Tech & AI",
    riasec: { R: 0.15, I: 0.75, A: 0.05, S: 0.1, E: 0.2, C: 0.65 },
    blurb: "Defends networks and data against threats — a mix of vigilance and technical depth.",
    skills: ["Network security", "Threat analysis", "Incident response", "Security certifications"],
    education: "Bachelor's common; certifications (Security+, CISSP) can substitute for part of a degree",
    degree: "bachelor",
    salary: "$95K – $165K (BLS median $124,910)",
    growth: "+29% through 2034 (BLS)",
    remote: "hybrid",
    setting: "indoor",
    collab: "mixed",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "datacenter-tech",
    title: "Datacenter Technician",
    category: "Tech & AI",
    riasec: { R: 0.75, I: 0.4, A: 0.05, S: 0.1, E: 0.05, C: 0.5 },
    blurb: "Keeps the physical servers powering the AI boom running — hands-on hardware work.",
    skills: ["Hardware troubleshooting", "Cabling & networking basics", "Physical stamina", "Safety protocols"],
    education: "No four-year degree required — technical certificate or on-the-job training",
    degree: "cert",
    salary: "$45K – $75K",
    growth: "#17 fastest-rising role, LinkedIn 2026",
    remote: "onsite",
    setting: "indoor",
    collab: "team",
    pace: "structured",
    risk: "growth"
  },
  {
    id: "nurse-practitioner",
    title: "Nurse Practitioner",
    category: "Healthcare",
    riasec: { R: 0.2, I: 0.6, A: 0.05, S: 0.9, E: 0.25, C: 0.35 },
    blurb: "Diagnoses, treats, and prescribes for patients with advanced clinical training.",
    skills: ["Clinical assessment", "Patient communication", "Empathy under pressure", "Evidence-based decision-making"],
    education: "Master's (MSN) or Doctorate (DNP) + RN licensure + national certification",
    degree: "graduate",
    salary: "$110K – $150K (BLS median $129,210)",
    growth: "+40% through 2034 (BLS) — fastest-growing healthcare role",
    remote: "onsite",
    setting: "indoor",
    collab: "team",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "physician-assistant",
    title: "Physician Assistant",
    category: "Healthcare",
    riasec: { R: 0.2, I: 0.65, A: 0.05, S: 0.85, E: 0.2, C: 0.35 },
    blurb: "Diagnoses and treats patients alongside physicians across nearly every specialty.",
    skills: ["Clinical diagnosis", "Procedural skills", "Teamwork", "Calm under pressure"],
    education: "Master's from an accredited PA program + licensure",
    degree: "graduate",
    salary: "$105K – $150K (BLS median $133,260)",
    growth: "+20%+ through 2034 (BLS)",
    remote: "onsite",
    setting: "indoor",
    collab: "team",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "pt-assistant",
    title: "Physical Therapist Assistant",
    category: "Healthcare",
    riasec: { R: 0.4, I: 0.35, A: 0.1, S: 0.85, E: 0.1, C: 0.3 },
    blurb: "Helps patients recover movement and strength through hands-on rehab exercises.",
    skills: ["Hands-on technique", "Patience", "Encouragement", "Basic anatomy knowledge"],
    education: "Associate degree from an accredited PTA program + licensure",
    degree: "cert",
    salary: "$55K – $78K (BLS median $65,510)",
    growth: "+22% through 2034 (BLS)",
    remote: "onsite",
    setting: "indoor",
    collab: "team",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "home-health-aide",
    title: "Home Health & Personal Care Aide",
    category: "Healthcare",
    riasec: { R: 0.35, I: 0.1, A: 0.05, S: 0.9, E: 0.05, C: 0.2 },
    blurb: "Provides daily care and companionship that lets people stay independent at home.",
    skills: ["Compassion", "Reliability", "Basic health monitoring", "Patience"],
    education: "No degree required — short-term on-the-job training/certification",
    degree: "none",
    salary: "$28K – $42K (BLS median $34,900)",
    growth: "+17% through 2034 — adds more jobs than any other US occupation (~740,000)",
    remote: "onsite",
    setting: "mixed",
    collab: "solo",
    pace: "flexible",
    risk: "stable"
  },
  {
    id: "health-services-manager",
    title: "Medical & Health Services Manager",
    category: "Healthcare",
    riasec: { R: 0.05, I: 0.35, A: 0.05, S: 0.55, E: 0.75, C: 0.65 },
    blurb: "Runs the business side of clinics and hospitals — budgets, staffing, and compliance.",
    skills: ["Leadership", "Budgeting", "Healthcare regulations", "Operations management"],
    education: "Bachelor's typical; master's common for senior roles",
    degree: "bachelor",
    salary: "$95K – $150K (BLS median $117,960)",
    growth: "+23% through 2034 (BLS)",
    remote: "onsite",
    setting: "indoor",
    collab: "team",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "psych-np",
    title: "Psychiatric Nurse Practitioner",
    category: "Healthcare",
    riasec: { R: 0.05, I: 0.55, A: 0.1, S: 0.9, E: 0.2, C: 0.3 },
    blurb: "Diagnoses and manages mental health conditions, including prescribing medication.",
    skills: ["Clinical psychiatry", "Deep empathy", "Crisis assessment", "Patient rapport"],
    education: "Master's (MSN) or Doctorate (DNP) with psychiatric specialization",
    degree: "graduate",
    salary: "$130K – $165K+",
    growth: "#19 fastest-rising role, LinkedIn 2026",
    remote: "hybrid",
    setting: "indoor",
    collab: "mixed",
    pace: "structured",
    risk: "growth"
  },
  {
    id: "mental-health-counselor",
    title: "Mental Health / Substance Abuse Counselor",
    category: "Healthcare",
    riasec: { R: 0.05, I: 0.4, A: 0.15, S: 0.95, E: 0.15, C: 0.25 },
    blurb: "Guides individuals and groups through recovery, coping, and behavioral change.",
    skills: ["Active listening", "Empathy", "Crisis intervention", "Group facilitation"],
    education: "Master's typical + state licensure",
    degree: "graduate",
    salary: "$45K – $75K (BLS median $59,190)",
    growth: "+17% through 2034 (BLS)",
    remote: "hybrid",
    setting: "indoor",
    collab: "mixed",
    pace: "flexible",
    risk: "stable"
  },
  {
    id: "electrician",
    title: "Electrician",
    category: "Skilled Trades",
    riasec: { R: 0.95, I: 0.35, A: 0.05, S: 0.15, E: 0.15, C: 0.4 },
    blurb: "Installs and repairs the electrical systems that power homes, buildings, and grids.",
    skills: ["Hands-on technical skill", "Blueprint reading", "Code compliance", "Troubleshooting"],
    education: "No four-year degree — high school diploma + paid apprenticeship + licensing",
    degree: "none",
    salary: "$52K – $106K+ (median ~$62,000; specialists higher)",
    growth: "+9.5% through 2034; industry needs ~349,000 net new trades workers in 2026 alone",
    remote: "onsite",
    setting: "mixed",
    collab: "mixed",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "hvac-tech",
    title: "HVAC Technician",
    category: "Skilled Trades",
    riasec: { R: 0.9, I: 0.35, A: 0.05, S: 0.15, E: 0.15, C: 0.4 },
    blurb: "Installs and services the heating, cooling, and ventilation systems buildings depend on.",
    skills: ["Mechanical aptitude", "Diagnostics", "Customer service", "Physical stamina"],
    education: "No four-year degree — trade school or apprenticeship + licensing",
    degree: "none",
    salary: "$48K – $85K",
    growth: "+8.1% through 2034 (BLS)",
    remote: "onsite",
    setting: "mixed",
    collab: "mixed",
    pace: "flexible",
    risk: "stable"
  },
  {
    id: "plumber",
    title: "Plumber",
    category: "Skilled Trades",
    riasec: { R: 0.9, I: 0.3, A: 0.05, S: 0.2, E: 0.2, C: 0.35 },
    blurb: "Installs and repairs the water, gas, and drainage systems every building needs.",
    skills: ["Hands-on repair", "Problem-solving", "Physical work", "Customer interaction"],
    education: "No four-year degree — apprenticeship + licensing",
    degree: "none",
    salary: "$50K – $95K",
    growth: "Steady demand; acute nationwide shortage of skilled trades workers",
    remote: "onsite",
    setting: "mixed",
    collab: "mixed",
    pace: "flexible",
    risk: "stable"
  },
  {
    id: "wind-turbine-tech",
    title: "Wind Turbine Technician",
    category: "Skilled Trades",
    riasec: { R: 0.95, I: 0.3, A: 0.05, S: 0.1, E: 0.1, C: 0.3 },
    blurb: "Maintains and repairs wind turbines — often hundreds of feet in the air.",
    skills: ["Mechanical/electrical aptitude", "Comfort with heights", "Physical fitness", "Safety discipline"],
    education: "No four-year degree — technical certificate or on-the-job training",
    degree: "cert",
    salary: "$50K – $80K (BLS median $62,580)",
    growth: "+50% through 2034 — fastest-growing US occupation (BLS)",
    remote: "onsite",
    setting: "outdoor",
    collab: "team",
    pace: "structured",
    risk: "growth"
  },
  {
    id: "solar-installer",
    title: "Solar Photovoltaic Installer",
    category: "Skilled Trades",
    riasec: { R: 0.9, I: 0.3, A: 0.05, S: 0.15, E: 0.15, C: 0.3 },
    blurb: "Installs and maintains solar panel systems on rooftops and solar farms.",
    skills: ["Mechanical/electrical aptitude", "Roof work", "Physical fitness", "Attention to safety"],
    education: "No four-year degree — technical certificate or on-the-job training",
    degree: "cert",
    salary: "$42K – $68K (BLS median $51,860)",
    growth: "+42% through 2034 — 2nd-fastest US occupation (BLS)",
    remote: "onsite",
    setting: "outdoor",
    collab: "team",
    pace: "structured",
    risk: "growth"
  },
  {
    id: "construction-lead",
    title: "Construction Project Lead",
    category: "Skilled Trades",
    riasec: { R: 0.65, I: 0.25, A: 0.1, S: 0.35, E: 0.65, C: 0.5 },
    blurb: "Coordinates crews, schedules, and budgets to bring building projects to life.",
    skills: ["Leadership", "Scheduling", "Budgeting", "On-site problem-solving"],
    education: "Varies — experience-based promotion common; degree helps for larger projects",
    degree: "cert",
    salary: "$65K – $110K",
    growth: "#22 fastest-rising role, LinkedIn 2026",
    remote: "onsite",
    setting: "outdoor",
    collab: "team",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "founder",
    title: "Founder / Entrepreneur",
    category: "Business & Self-Directed",
    riasec: { R: 0.15, I: 0.4, A: 0.35, S: 0.35, E: 0.95, C: 0.15 },
    blurb: "Builds something from nothing — product, team, and business all at once.",
    skills: ["Self-direction", "Sales & fundraising", "Resilience", "Financial literacy"],
    education: "No fixed requirement — varies enormously by industry",
    degree: "none",
    salary: "Highly variable — often $0 to start, unbounded upside",
    growth: "#9 fastest-rising role, LinkedIn 2026",
    remote: "flexible",
    setting: "indoor",
    collab: "mixed",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "strategic-advisor",
    title: "Strategic Advisor & Independent Consultant",
    category: "Business & Self-Directed",
    riasec: { R: 0.05, I: 0.55, A: 0.15, S: 0.45, E: 0.85, C: 0.35 },
    blurb: "Sells deep expertise directly to organizations that need outside perspective.",
    skills: ["Domain expertise", "Business development", "Communication", "Self-management"],
    education: "Varies widely — deep prior experience matters more than credentials",
    degree: "bachelor",
    salary: "Highly variable — often $100K – $300K+",
    growth: "#7 fastest-rising role, LinkedIn 2026",
    remote: "flexible",
    setting: "indoor",
    collab: "solo",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "financial-advisor",
    title: "Financial Advisor & Planner",
    category: "Business & Self-Directed",
    riasec: { R: 0.05, I: 0.4, A: 0.05, S: 0.65, E: 0.75, C: 0.55 },
    blurb: "Helps individuals and families plan for retirement, savings, and big financial decisions.",
    skills: ["Financial modeling", "Client relationships", "Trustworthiness", "Sales ability"],
    education: "Bachelor's typical; CFP certification valued",
    degree: "bachelor",
    salary: "$70K – $150K+ (often commission-based)",
    growth: "#21 fastest-rising role, LinkedIn 2026",
    remote: "hybrid",
    setting: "indoor",
    collab: "mixed",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "actuary",
    title: "Actuary",
    category: "Business & Self-Directed",
    riasec: { R: 0.05, I: 0.85, A: 0.05, S: 0.15, E: 0.2, C: 0.75 },
    blurb: "Uses statistics and probability to quantify financial risk for insurers and firms.",
    skills: ["Advanced statistics", "Financial modeling", "Professional exams", "Precision"],
    education: "Bachelor's + progression through professional actuarial exams",
    degree: "bachelor",
    salary: "$95K – $160K (BLS median $125,770)",
    growth: "+22% through 2034 (BLS)",
    remote: "hybrid",
    setting: "indoor",
    collab: "solo",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "operations-research-analyst",
    title: "Operations Research Analyst",
    category: "Business & Self-Directed",
    riasec: { R: 0.1, I: 0.85, A: 0.1, S: 0.15, E: 0.25, C: 0.6 },
    blurb: "Uses math and data modeling to solve complex logistics and business problems.",
    skills: ["Statistics", "Optimization modeling", "Programming", "Analytical writing"],
    education: "Bachelor's or master's in a quantitative field",
    degree: "bachelor",
    salary: "$70K – $115K (BLS median $91,290)",
    growth: "+21% through 2034 (BLS)",
    remote: "hybrid",
    setting: "indoor",
    collab: "mixed",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "ux-designer",
    title: "UX/UI Designer",
    category: "Creative & Digital",
    riasec: { R: 0.05, I: 0.4, A: 0.9, S: 0.4, E: 0.25, C: 0.2 },
    blurb: "Designs how digital products look, feel, and work for real people.",
    skills: ["User research", "Wireframing / prototyping (Figma)", "Visual design", "Usability testing"],
    education: "Bachelor's common but not required — portfolio and bootcamp paths are viable",
    degree: "none",
    salary: "$85K – $140K",
    growth: "WEF projects ~48% global growth for UI/UX design roles",
    remote: "remote",
    setting: "indoor",
    collab: "mixed",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "digital-marketing",
    title: "Digital Marketing Specialist",
    category: "Creative & Digital",
    riasec: { R: 0.05, I: 0.3, A: 0.6, S: 0.4, E: 0.65, C: 0.35 },
    blurb: "Plans and runs campaigns across search, social, and content to grow an audience.",
    skills: ["Content strategy", "Analytics", "Copywriting", "Campaign management"],
    education: "Bachelor's common, not always required — strong portfolios substitute",
    degree: "none",
    salary: "$55K – $95K",
    growth: "Steady growth as brands shift budgets to digital and AI-assisted marketing",
    remote: "remote",
    setting: "indoor",
    collab: "mixed",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "sustainability-manager",
    title: "Sustainability Manager / ESG Specialist",
    category: "Sustainability",
    riasec: { R: 0.1, I: 0.55, A: 0.1, S: 0.45, E: 0.55, C: 0.55 },
    blurb: "Leads a company's environmental and social responsibility strategy and reporting.",
    skills: ["Environmental literacy", "Data analysis", "ESG reporting", "Stakeholder communication"],
    education: "Bachelor's typical, often plus applied experience or credentials",
    degree: "bachelor",
    salary: "$80K – $150K (avg. ~$125K)",
    growth: "Steady rise as ESG reporting requirements expand",
    remote: "hybrid",
    setting: "indoor",
    collab: "team",
    pace: "structured",
    risk: "growth"
  },
  {
    id: "environmental-engineer",
    title: "Environmental Engineer",
    category: "Sustainability",
    riasec: { R: 0.4, I: 0.8, A: 0.1, S: 0.2, E: 0.2, C: 0.45 },
    blurb: "Designs solutions for clean water, air quality, and sustainable infrastructure.",
    skills: ["Engineering fundamentals", "Environmental regulations", "Data modeling", "Project design"],
    education: "Bachelor's in environmental or civil engineering",
    degree: "bachelor",
    salary: "$75K – $120K",
    growth: "WEF ranks renewable/environmental engineering among top-15 fastest-growing global roles",
    remote: "hybrid",
    setting: "mixed",
    collab: "team",
    pace: "structured",
    risk: "growth"
  },
  {
    id: "business-dev",
    title: "Business Development / Advertising Sales Specialist",
    category: "Business & Self-Directed",
    riasec: { R: 0.05, I: 0.2, A: 0.2, S: 0.55, E: 0.95, C: 0.25 },
    blurb: "Builds relationships and closes deals that grow a company's revenue.",
    skills: ["Persuasion", "Relationship-building", "Negotiation", "Resilience to rejection"],
    education: "Bachelor's common but experience and results often matter more",
    degree: "bachelor",
    salary: "$60K – $150K+ (often commission-based)",
    growth: "#8 & #16 fastest-rising roles, LinkedIn 2026",
    remote: "hybrid",
    setting: "indoor",
    collab: "team",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "travel-advisor",
    title: "Travel Advisor",
    category: "Business & Self-Directed",
    riasec: { R: 0.05, I: 0.2, A: 0.3, S: 0.7, E: 0.55, C: 0.35 },
    blurb: "Plans and books tailored trips, drawing on destination expertise and client trust.",
    skills: ["Destination knowledge", "Client service", "Organization", "Sales"],
    education: "No degree required — certification programs available",
    degree: "none",
    salary: "$40K – $75K (often commission-based)",
    growth: "#18 fastest-rising role, LinkedIn 2026",
    remote: "remote",
    setting: "indoor",
    collab: "solo",
    pace: "flexible",
    risk: "growth"
  }
];
