/* ============================================================
   Suretofind — Ireland Job Dataset
   Compiled from: Ireland's Critical Skills Occupations List 2026
   (Dept. of Enterprise, Tourism and Employment), the CSO Labour
   Force Survey, the Morgan McKinley Ireland Salary Guide 2026,
   the Expert Group on Future Skills Needs (EGFSN), Excel
   Recruitment's Healthcare and Hotel & Catering Salary Guides,
   and Fáilte Ireland workforce reporting.

   riasec values are 0–1 weights on Holland's six types:
   R = Realistic, I = Investigative, A = Artistic,
   S = Social, E = Enterprising, C = Conventional

   degree: "none" | "cert" | "bachelor" | "graduate"
   remote: "remote" | "hybrid" | "onsite" | "flexible"
   setting: "indoor" | "outdoor" | "mixed"
   collab: "solo" | "team" | "mixed"
   pace: "structured" | "flexible"
   risk: "stable" | "growth"   (stable = established/steady demand,
                                  growth = fast-rising / more volatile)
   ============================================================ */

const JOBS_IE = [
  {
    id: "software-engineer-ie",
    title: "Software Engineer / Developer",
    category: "Tech & AI",
    riasec: { R: 0.1, I: 0.85, A: 0.35, S: 0.15, E: 0.25, C: 0.45 },
    blurb: "Builds and maintains the software behind Ireland's cluster of tech multinationals and homegrown scale-ups.",
    skills: ["Programming (JavaScript/Python/Java)", "System design", "Version control (Git)", "Debugging", "Agile teamwork"],
    education: "Level 8 honours degree in computer science or related field common; bootcamp/portfolio routes increasingly accepted",
    degree: "bachelor",
    salary: "€40K – €70K entry-level, €70K – €100K+ experienced",
    growth: "Software Development ranks #1 on Ireland's Critical Skills Occupations List 2026 (DETE)",
    remote: "hybrid",
    setting: "indoor",
    collab: "mixed",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "ai-ml-engineer-ie",
    title: "AI / Machine Learning Engineer",
    category: "Tech & AI",
    riasec: { R: 0.1, I: 0.95, A: 0.3, S: 0.15, E: 0.3, C: 0.4 },
    blurb: "Builds and deploys the machine learning systems being adopted across Dublin's tech and finance hubs.",
    skills: ["Python", "ML frameworks (PyTorch/TensorFlow)", "MLOps", "Statistics", "Cloud platforms"],
    education: "Level 8 degree in CS, data science, or a related quantitative field; postgraduate qualifications increasingly common",
    degree: "bachelor",
    salary: "€80K – €120K+",
    growth: "AI/ML job postings up 40%+ year-on-year — the fastest-growing tech category in Ireland (2026)",
    remote: "hybrid",
    setting: "indoor",
    collab: "mixed",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "data-scientist-ie",
    title: "Data Scientist / Data Analyst",
    category: "Tech & AI",
    riasec: { R: 0.05, I: 0.9, A: 0.15, S: 0.15, E: 0.2, C: 0.55 },
    blurb: "Turns data into decisions for Ireland's financial services, tech, and pharma sectors.",
    skills: ["Statistics", "Python / R", "SQL", "Data visualisation", "Business storytelling"],
    education: "Level 8 degree in a quantitative field typical; master's common for senior roles",
    degree: "bachelor",
    salary: "€55K – €95K",
    growth: "Listed among Ireland's top in-demand tech roles for 2026 (Critical Skills Occupations List)",
    remote: "hybrid",
    setting: "indoor",
    collab: "mixed",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "cybersecurity-analyst-ie",
    title: "Cybersecurity Analyst",
    category: "Tech & AI",
    riasec: { R: 0.15, I: 0.75, A: 0.05, S: 0.1, E: 0.2, C: 0.65 },
    blurb: "Protects the networks and data of Ireland's dense cluster of tech and financial multinationals.",
    skills: ["Network security", "Threat detection", "Incident response", "Security certifications (CISSP/Security+)"],
    education: "Level 8 degree common; certifications can substitute for part of a degree",
    degree: "bachelor",
    salary: "€55K – €95K",
    growth: "Named a recognised shortage occupation on Ireland's Critical Skills Occupations List 2026",
    remote: "hybrid",
    setting: "indoor",
    collab: "mixed",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "datacenter-tech-ie",
    title: "Data Centre Technician",
    category: "Tech & AI",
    riasec: { R: 0.75, I: 0.4, A: 0.05, S: 0.1, E: 0.05, C: 0.5 },
    blurb: "Keeps the physical servers running behind Dublin's status as one of Europe's largest data centre hubs.",
    skills: ["Hardware troubleshooting", "Cabling & networking basics", "Physical stamina", "Safety protocols"],
    education: "QQI Level 5/6 technical certificate or on-the-job training — no degree required",
    degree: "cert",
    salary: "€35K – €55K",
    growth: "Steady demand as Ireland's data centre footprint, concentrated around Dublin, keeps expanding",
    remote: "onsite",
    setting: "indoor",
    collab: "team",
    pace: "structured",
    risk: "growth"
  },
  {
    id: "staff-nurse-ie",
    title: "Staff Nurse (HSE)",
    category: "Healthcare",
    riasec: { R: 0.2, I: 0.6, A: 0.05, S: 0.9, E: 0.2, C: 0.4 },
    blurb: "Delivers frontline clinical care across HSE hospitals, community, and mental health services.",
    skills: ["Clinical assessment", "Patient communication", "Empathy under pressure", "Evidence-based care"],
    education: "Level 8 BSc in General Nursing (or relevant specialism) + NMBI registration",
    degree: "bachelor",
    salary: "€38,166 – €56,592 (HSE staff nurse pay scale, 2026)",
    growth: "Nursing is a recognised shortage occupation; the HSE is actively recruiting domestically and internationally",
    remote: "onsite",
    setting: "indoor",
    collab: "team",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "healthcare-assistant-ie",
    title: "Healthcare Assistant",
    category: "Healthcare",
    riasec: { R: 0.35, I: 0.1, A: 0.05, S: 0.9, E: 0.05, C: 0.25 },
    blurb: "Provides hands-on daily care to patients in hospitals, nursing homes, and home settings.",
    skills: ["Compassion", "Reliability", "Basic health monitoring", "Patience"],
    education: "QQI Level 5 Healthcare Support award typical — no degree required",
    degree: "cert",
    salary: "€29K – €38K (post-February 2026 HSE pay revision)",
    growth: "Persistent shortage across the HSE and private nursing homes",
    remote: "onsite",
    setting: "indoor",
    collab: "team",
    pace: "flexible",
    risk: "stable"
  },
  {
    id: "physiotherapist-ie",
    title: "Physiotherapist",
    category: "Healthcare",
    riasec: { R: 0.4, I: 0.55, A: 0.1, S: 0.85, E: 0.15, C: 0.3 },
    blurb: "Helps patients recover movement and manage pain through hands-on rehabilitation.",
    skills: ["Clinical assessment", "Hands-on technique", "Patient education", "Care planning"],
    education: "Level 8 BSc in Physiotherapy + CORU registration",
    degree: "bachelor",
    salary: "€40K – €62K",
    growth: "Recognised shortage occupation on Ireland's Critical Skills Occupations List 2026",
    remote: "onsite",
    setting: "indoor",
    collab: "team",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "pharmacist-ie",
    title: "Pharmacist",
    category: "Healthcare",
    riasec: { R: 0.1, I: 0.7, A: 0.05, S: 0.55, E: 0.25, C: 0.6 },
    blurb: "Dispenses medicines and advises patients across community pharmacy and hospital settings.",
    skills: ["Pharmacology", "Attention to detail", "Patient counselling", "Regulatory compliance"],
    education: "Level 9 MPharm (integrated master's) + PSI registration",
    degree: "graduate",
    salary: "€50K – €75K",
    growth: "Recognised shortage occupation on Ireland's Critical Skills Occupations List 2026",
    remote: "onsite",
    setting: "indoor",
    collab: "mixed",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "social-care-worker-ie",
    title: "Social Care Worker",
    category: "Healthcare",
    riasec: { R: 0.15, I: 0.3, A: 0.1, S: 0.95, E: 0.15, C: 0.25 },
    blurb: "Supports children, people with disabilities, or vulnerable adults through direct, relationship-based care.",
    skills: ["Empathy", "Crisis management", "Care planning", "Teamwork"],
    education: "Level 8 degree in Social Care + CORU registration",
    degree: "bachelor",
    salary: "€33K – €48K",
    growth: "Steady demand across HSE, Tusla, and disability/community services",
    remote: "onsite",
    setting: "indoor",
    collab: "team",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "biopharma-tech-ie",
    title: "Biopharma Manufacturing Technician",
    category: "Pharma & Life Sciences",
    riasec: { R: 0.65, I: 0.5, A: 0.05, S: 0.15, E: 0.1, C: 0.65 },
    blurb: "Runs and monitors the production lines inside Ireland's biopharmaceutical manufacturing plants.",
    skills: ["GMP manufacturing", "Process monitoring", "Documentation & compliance", "Equipment troubleshooting"],
    education: "QQI Level 6 certificate or apprenticeship typical — no degree required to enter",
    degree: "cert",
    salary: "€35K – €55K (average pharma manufacturing salary ~€62K with experience)",
    growth: "EGFSN forecasts 21,000+ new pharma/biopharma jobs in Ireland by 2027",
    remote: "onsite",
    setting: "indoor",
    collab: "team",
    pace: "structured",
    risk: "growth"
  },
  {
    id: "medical-science-ie",
    title: "Medical Science / QC Scientist",
    category: "Pharma & Life Sciences",
    riasec: { R: 0.2, I: 0.85, A: 0.05, S: 0.2, E: 0.15, C: 0.6 },
    blurb: "Runs lab analysis and quality testing for pharma, biotech, and hospital labs.",
    skills: ["Lab techniques", "Quality control / GMP", "Data analysis", "Precision"],
    education: "Level 8 degree in a life science, chemistry, or medical science field",
    degree: "bachelor",
    salary: "€45K – €65K",
    growth: "Named on Ireland's Critical Skills Occupations List (biochemist / medical laboratory scientist roles)",
    remote: "onsite",
    setting: "indoor",
    collab: "mixed",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "electrician-ie",
    title: "Electrician",
    category: "Skilled Trades & Construction",
    riasec: { R: 0.95, I: 0.35, A: 0.05, S: 0.15, E: 0.15, C: 0.4 },
    blurb: "Installs and maintains the electrical systems powering homes, data centres, and the EV/solar transition.",
    skills: ["Hands-on technical skill", "Blueprint reading", "Code compliance", "Troubleshooting"],
    education: "No degree — Leaving Cert + 4-year SOLAS electrical apprenticeship + licensing",
    degree: "none",
    salary: "€45K – €57K qualified (apprentices ~€21K – €37K, rising through training phases)",
    growth: "Demand climbing fast — driven by the housing shortage, data centre construction, and the EV/solar rollout",
    remote: "onsite",
    setting: "mixed",
    collab: "mixed",
    pace: "structured",
    risk: "growth"
  },
  {
    id: "plumber-ie",
    title: "Plumber",
    category: "Skilled Trades & Construction",
    riasec: { R: 0.9, I: 0.3, A: 0.05, S: 0.2, E: 0.2, C: 0.35 },
    blurb: "Installs and repairs the water, heating, and drainage systems every building depends on.",
    skills: ["Hands-on repair", "Problem-solving", "Physical work", "Customer interaction"],
    education: "No degree — Leaving Cert + apprenticeship + licensing",
    degree: "none",
    salary: "€40K – €60K qualified",
    growth: "Steady, high demand amid the national housing shortage and ongoing skilled-trades shortfall",
    remote: "onsite",
    setting: "mixed",
    collab: "mixed",
    pace: "flexible",
    risk: "stable"
  },
  {
    id: "quantity-surveyor-ie",
    title: "Quantity Surveyor",
    category: "Skilled Trades & Construction",
    riasec: { R: 0.3, I: 0.55, A: 0.05, S: 0.2, E: 0.35, C: 0.6 },
    blurb: "Manages costs and contracts on construction projects, from housing schemes to data centres.",
    skills: ["Cost estimation", "Contract management", "Construction knowledge", "Negotiation"],
    education: "Level 8 degree in quantity surveying / construction economics + SCSI chartership",
    degree: "bachelor",
    salary: "€45K – €75K",
    growth: "Recognised shortage occupation on Ireland's Critical Skills Occupations List 2026",
    remote: "hybrid",
    setting: "mixed",
    collab: "team",
    pace: "structured",
    risk: "growth"
  },
  {
    id: "construction-pm-ie",
    title: "Construction Project Manager",
    category: "Skilled Trades & Construction",
    riasec: { R: 0.65, I: 0.25, A: 0.1, S: 0.35, E: 0.65, C: 0.5 },
    blurb: "Coordinates crews, schedules, and budgets to deliver Ireland's housing and infrastructure pipeline.",
    skills: ["Leadership", "Scheduling", "Budgeting", "On-site problem-solving"],
    education: "Varies — experience-based promotion common; a construction/engineering degree helps for larger projects",
    degree: "cert",
    salary: "€55K – €90K",
    growth: "Strong demand — construction employment grew +29,600 jobs (+18.4%) in the year to 2026 (CSO)",
    remote: "onsite",
    setting: "outdoor",
    collab: "team",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "wind-turbine-tech-ie",
    title: "Offshore Wind Technician",
    category: "Renewable Energy",
    riasec: { R: 0.95, I: 0.3, A: 0.05, S: 0.1, E: 0.1, C: 0.3 },
    blurb: "Installs and maintains the turbines behind Ireland's growing offshore wind buildout off the Celtic Sea coast.",
    skills: ["Mechanical/electrical aptitude", "Comfort with heights and sea conditions", "Physical fitness", "Safety discipline"],
    education: "QQI technical certificate or GWO safety training — no degree required",
    degree: "cert",
    salary: "€40K – €65K",
    growth: "Emerging sector as Ireland scales offshore wind capacity to meet national renewable-energy targets",
    remote: "onsite",
    setting: "outdoor",
    collab: "team",
    pace: "structured",
    risk: "growth"
  },
  {
    id: "solar-installer-ie",
    title: "Solar PV Installer",
    category: "Renewable Energy",
    riasec: { R: 0.9, I: 0.3, A: 0.05, S: 0.15, E: 0.15, C: 0.3 },
    blurb: "Installs and maintains solar panel systems on homes, farms, and commercial rooftops.",
    skills: ["Mechanical/electrical aptitude", "Roof work", "Physical fitness", "Attention to safety"],
    education: "QQI technical certificate or on-the-job training — no degree required",
    degree: "cert",
    salary: "€35K – €55K",
    growth: "Growing steadily alongside Ireland's residential and commercial solar uptake",
    remote: "onsite",
    setting: "outdoor",
    collab: "team",
    pace: "structured",
    risk: "growth"
  },
  {
    id: "accountant-ie",
    title: "Chartered / Financial Accountant",
    category: "Business & Finance",
    riasec: { R: 0.05, I: 0.6, A: 0.05, S: 0.3, E: 0.35, C: 0.75 },
    blurb: "Manages accounts, reporting, and compliance for Irish and multinational businesses.",
    skills: ["Financial reporting", "Regulatory compliance", "Analysis", "Attention to detail"],
    education: "Level 8 degree + professional accountancy exams (ACA/ACCA/CPA)",
    degree: "bachelor",
    salary: "€60K – €65K newly qualified, €70K – €90K+ experienced (Morgan McKinley Ireland Salary Guide 2026)",
    growth: "Chartered accountants remain on Ireland's Critical Skills Occupations List",
    remote: "hybrid",
    setting: "indoor",
    collab: "mixed",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "actuary-ie",
    title: "Actuary",
    category: "Business & Finance",
    riasec: { R: 0.05, I: 0.85, A: 0.05, S: 0.15, E: 0.2, C: 0.75 },
    blurb: "Uses statistics and probability to quantify financial risk for Ireland's large insurance and reinsurance sector.",
    skills: ["Advanced statistics", "Financial modelling", "Professional exams", "Precision"],
    education: "Level 8 degree + progression through professional actuarial exams",
    degree: "bachelor",
    salary: "€55K – €95K+",
    growth: "A recognised shortage occupation within Ireland's financial services sector",
    remote: "hybrid",
    setting: "indoor",
    collab: "solo",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "fintech-analyst-ie",
    title: "Financial Services / FinTech Analyst",
    category: "Business & Finance",
    riasec: { R: 0.05, I: 0.55, A: 0.1, S: 0.35, E: 0.55, C: 0.65 },
    blurb: "Analyses markets, risk, and products for Dublin's IFSC banking, funds, and fintech firms.",
    skills: ["Financial analysis", "Regulatory knowledge", "Data tools", "Communication"],
    education: "Level 8 degree in finance, business, or a related field; professional qualifications valued",
    degree: "bachelor",
    salary: "€45K – €75K",
    growth: "Financial services and fintech feature among Ireland's top in-demand sectors for 2026",
    remote: "hybrid",
    setting: "indoor",
    collab: "team",
    pace: "structured",
    risk: "growth"
  },
  {
    id: "teacher-ie",
    title: "Primary / Secondary School Teacher",
    category: "Education",
    riasec: { R: 0.1, I: 0.45, A: 0.35, S: 0.9, E: 0.3, C: 0.4 },
    blurb: "Teaches and mentors students through Ireland's primary or post-primary curriculum.",
    skills: ["Lesson planning", "Classroom management", "Communication", "Patience"],
    education: "Level 8 B.Ed, or a primary degree + Professional Master of Education (PME)",
    degree: "bachelor",
    salary: "€43,774 – €86,265 across the pay scale (2026)",
    growth: "Recruitment shortages persist, especially in STEM, Irish, and Dublin-area schools",
    remote: "onsite",
    setting: "indoor",
    collab: "team",
    pace: "structured",
    risk: "stable"
  },
  {
    id: "chef-ie",
    title: "Chef",
    category: "Hospitality & Tourism",
    riasec: { R: 0.6, I: 0.2, A: 0.55, S: 0.3, E: 0.15, C: 0.3 },
    blurb: "Runs the kitchen — planning menus, prepping food, and leading a fast-paced service team.",
    skills: ["Culinary technique", "Kitchen management", "Working under pressure", "Creativity with food"],
    education: "No degree required — apprenticeship, culinary college, or on-the-job training",
    degree: "none",
    salary: "€34K – €47K (senior chefs up to ~€53K)",
    growth: "Chefs are the most common hospitality work-permit category — 88% of employers report hiring difficulty (Fáilte Ireland)",
    remote: "onsite",
    setting: "indoor",
    collab: "team",
    pace: "structured",
    risk: "growth"
  },
  {
    id: "hospitality-manager-ie",
    title: "Hotel & Hospitality Manager",
    category: "Hospitality & Tourism",
    riasec: { R: 0.1, I: 0.25, A: 0.25, S: 0.7, E: 0.75, C: 0.45 },
    blurb: "Runs the day-to-day operations of a hotel, restaurant, or tourism business.",
    skills: ["Leadership", "Customer service", "Budgeting", "Operations management"],
    education: "No fixed requirement — a hospitality management degree or diploma is common, and experience-based promotion is frequent",
    degree: "cert",
    salary: "€35K – €55K",
    growth: "Tourism and hospitality continue rebuilding staffing levels amid an ongoing sector-wide labour shortage",
    remote: "onsite",
    setting: "indoor",
    collab: "team",
    pace: "flexible",
    risk: "stable"
  },
  {
    id: "agri-technician-ie",
    title: "Farm / Agri-Food Technician",
    category: "Agriculture",
    riasec: { R: 0.85, I: 0.35, A: 0.05, S: 0.15, E: 0.25, C: 0.35 },
    blurb: "Manages livestock, land, or dairy operations within Ireland's largest indigenous industry.",
    skills: ["Animal/land husbandry", "Machinery operation", "Business basics", "Physical stamina"],
    education: "QQI / Teagasc agricultural certificate — no university degree required",
    degree: "cert",
    salary: "€30K – €48K (varies with enterprise scale)",
    growth: "Steady demand — agri-food remains Ireland's largest indigenous employer, with ongoing labour shortages on farms",
    remote: "onsite",
    setting: "outdoor",
    collab: "solo",
    pace: "flexible",
    risk: "stable"
  },
  {
    id: "ux-designer-ie",
    title: "UX/UI Designer",
    category: "Creative & Digital",
    riasec: { R: 0.05, I: 0.4, A: 0.9, S: 0.4, E: 0.25, C: 0.2 },
    blurb: "Designs how digital products look, feel, and work for Ireland's tech and scale-up sector.",
    skills: ["User research", "Wireframing / prototyping (Figma)", "Visual design", "Usability testing"],
    education: "Degree common but not required — portfolio and bootcamp routes are viable",
    degree: "none",
    salary: "€40K – €70K",
    growth: "Strong demand across Dublin's concentration of tech multinational and product teams",
    remote: "remote",
    setting: "indoor",
    collab: "mixed",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "digital-marketing-ie",
    title: "Digital Marketing Specialist",
    category: "Creative & Digital",
    riasec: { R: 0.05, I: 0.3, A: 0.6, S: 0.4, E: 0.65, C: 0.35 },
    blurb: "Plans and runs campaigns across search, social, and content for Irish and multinational brands.",
    skills: ["Content strategy", "Analytics", "Copywriting", "Campaign management"],
    education: "Degree common, not always required — strong portfolios substitute",
    degree: "none",
    salary: "€35K – €55K",
    growth: "Steady growth as Irish brands shift budgets into digital and AI-assisted marketing",
    remote: "remote",
    setting: "indoor",
    collab: "mixed",
    pace: "flexible",
    risk: "growth"
  },
  {
    id: "business-dev-ie",
    title: "Business Development / Sales Specialist",
    category: "Business & Finance",
    riasec: { R: 0.05, I: 0.2, A: 0.2, S: 0.55, E: 0.95, C: 0.25 },
    blurb: "Builds relationships and closes deals for Dublin's dense cluster of tech and services multinationals.",
    skills: ["Persuasion", "Relationship-building", "Negotiation", "Resilience to rejection"],
    education: "Degree common but experience and results often matter more",
    degree: "bachelor",
    salary: "€40K – €70K base (often with commission/OTE on top)",
    growth: "Consistently in demand across Dublin's multinational sales hubs",
    remote: "hybrid",
    setting: "indoor",
    collab: "team",
    pace: "flexible",
    risk: "growth"
  }
];
